---
abstract: 'Carp::Always, but with color'
author:
  - 'Jesse Luehrs <doy at tozt dot net>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101151'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Carp-Always-Color
recommends: {}
requires:
  Carp::Always: 0
version: 0.03
